### ISSUE TITLE
Chromatogram deconvolution step in workflow

### ISSUE THREAD

**Issue by Adafede** [DorresteinLaboratory/XCMS3_FeatureBasedMN#13]
Hi,

Trying now all possibilities you offer within GNPS, I was wondering why there is no chromatogram deconvolution step (allowing to split those "npeaks" column) proposed in your XCMS workflow? Did I just miss it or is there any particular reason? Is it going to be implemented in further developments?

Many thanks in advance

**Comment by lfnothias** [comment]
I am not expert by XCMS by all means, but I am pretty sure there is such a step
@jorainer ?

**Comment by jorainer** [comment]
Dear @Adafede could you please elaborate a little on this? I don't quite understand what you want to do and what you mean with *chromatogram deconvolution step* in relation to the *npeaks* column?

The *npeaks* column lists the total number of chromatographic peaks (identified in all samples) that have been assigned to this one feature.

**Comment by Adafede** [comment]
Dear @jorainer , thank you very much for your answer!

What I would like is to have one feature (one line) per chromatographic peak. (possibly with multiple MS2 scans associated, possibly found in multiple samples), but not all the chromatographic peaks over a chromatogram. (Something like "gather" every single chromatographic peak)
I don't know if it is clearer yet. So that always _npeaks_ = 1 and something like _nscans_ in a chromatographic peak = 1,2,3,4... like your _npeaks_ now

As an example:

_m/z_ 100.0000 @ 2.12 RT : 1 MS2 scan in sample A, 2 MS2 scans in sample B @ 2.13 RT, total _nscans_ = 3 (chromatographic peak going from 2.10 to 2.20), but _npeaks_ = 1

_m/z_ 100.0000 @ 7.15 RT : 3 MS2 scan in sample A, 3 MS2 scans in sample B @ 7.18 RT, total _nscans_ = 6 (chromatographic peak going from 7.10 to 7.20), but _npeaks_ = 1

Hope it helps

**Comment by jorainer** [comment]
If I understood correctly you would like to have the chromatographic peaks **before** the correspondence analysis in which chromatographic peaks get grouped across samples.

You should have all the tools available to do that in `xcms`. With `chromPeakSpectra` you would get all MS2 spectra that are associated with any chromatographic peak in a sample. 

On the other hand, when you follow the workflow and you called `featureSpectra` (and thus have the `filteredMs2Spectra` variable), you could also get some of this information from that object. The object is essentially a list of MS2 spectra:

```r
> filteredMs2Spectra
Spectra with 49561 spectra and 2 metadata column(s):
                             msLevel     rtime peaksCount |  feature_id
                           <integer> <numeric>  <integer> | <character>
  FT0006.CP02887.F01.S4887         2   767.064          4 |      FT0006
  FT0006.CP02887.F01.S4923         2   770.735          1 |      FT0006
                       ...       ...       ...        ... .         ...
  FT3194.CP70770.F21.S1823         2   286.579        363 |      FT3194
  FT3194.CP70770.F21.S1829         2   287.456        370 |      FT3194
                               peak_id
                           <character>
  FT0006.CP02887.F01.S4887     CP02887
  FT0006.CP02887.F01.S4923     CP02887
                       ...         ...
  FT3194.CP70770.F21.S1823     CP70770
  FT3194.CP70770.F21.S1829     CP70770
```

The *column* `"feature_id"` tells you to which feature the MS2 spectrum can be associated with, while `"peak_id"` is the ID for the actual chromatographic peak in one sample (this ID matches the `rownames` of `chromPeaks` and `chromPeakData` of the `xcms` result object). You could now for example also call `fromFile` on this object to get the information in which original file (sample) the MS2 was measured. Below we extract this information and add this as an additional *metadata column*:

```r
> mcols(filteredMs2Spectra)$sample_idx <- fromFile(filteredMs2Spectra)
> filteredMs2Spectra
Spectra with 49561 spectra and 3 metadata column(s):
                             msLevel     rtime peaksCount |  feature_id
                           <integer> <numeric>  <integer> | <character>
  FT0006.CP02887.F01.S4887         2   767.064          4 |      FT0006
  FT0006.CP02887.F01.S4923         2   770.735          1 |      FT0006
                       ...       ...       ...        ... .         ...
  FT3194.CP70770.F21.S1823         2   286.579        363 |      FT3194
  FT3194.CP70770.F21.S1829         2   287.456        370 |      FT3194
                               peak_id sample_idx
                           <character>  <integer>
  FT0006.CP02887.F01.S4887     CP02887          1
  FT0006.CP02887.F01.S4923     CP02887          1
                       ...         ...        ...
  FT3194.CP70770.F21.S1823     CP70770         21
  FT3194.CP70770.F21.S1829     CP70770         21
```

... hope this helps somehow, otherwise just let me know what exactly you would like to get and we'll find a way.

Eventually also have a look [here](https://bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms-lcms-ms.html) for some related info.
